// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChWG5R63zNSnrQovToqHtr20UyMQUTdmk',
    appId: '1:724092263477:web:a7c851e8ef01f05129e57c',
    messagingSenderId: '724092263477',
    projectId: 'codepulse-57666',
    authDomain: 'codepulse-57666.firebaseapp.com',
    storageBucket: 'codepulse-57666.firebasestorage.app',
    measurementId: 'G-D75HPPM9B6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU8-si5z-laoZ_b27YeE2mE_hd7JpApWk',
    appId: '1:724092263477:android:f56c13dcc37f09d029e57c',
    messagingSenderId: '724092263477',
    projectId: 'codepulse-57666',
    storageBucket: 'codepulse-57666.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqoWEOMOs1PPkTFfbVszdYf1eyg-5WAUw',
    appId: '1:724092263477:ios:3bb33567f3b35ef229e57c',
    messagingSenderId: '724092263477',
    projectId: 'codepulse-57666',
    storageBucket: 'codepulse-57666.firebasestorage.app',
    iosBundleId: 'com.example.codeAssistant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqoWEOMOs1PPkTFfbVszdYf1eyg-5WAUw',
    appId: '1:724092263477:ios:3bb33567f3b35ef229e57c',
    messagingSenderId: '724092263477',
    projectId: 'codepulse-57666',
    storageBucket: 'codepulse-57666.firebasestorage.app',
    iosBundleId: 'com.example.codeAssistant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChWG5R63zNSnrQovToqHtr20UyMQUTdmk',
    appId: '1:724092263477:web:f8659049ddc96b9e29e57c',
    messagingSenderId: '724092263477',
    projectId: 'codepulse-57666',
    authDomain: 'codepulse-57666.firebaseapp.com',
    storageBucket: 'codepulse-57666.firebasestorage.app',
    measurementId: 'G-6N4C4YY9D1',
  );
}
